// <auto-generated />
using System;
using MOJTechTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MojTechTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MOJTechTest.Models.CaseTask", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("case_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<DateTime>("due")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            id = 1,
                            case_id = "A6429",
                            due = new DateTime(2025, 6, 12, 10, 30, 0, 0, DateTimeKind.Utc),
                            status = "To do",
                            title = "Read Chapter 1, Section 1.1.3"
                        },
                        new
                        {
                            id = 2,
                            case_id = "A1745",
                            due = new DateTime(2025, 6, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            status = "In Progress",
                            title = "Complete the design a protocol activity"
                        },
                        new
                        {
                            id = 3,
                            case_id = "A6833",
                            due = new DateTime(2025, 6, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            status = "Done",
                            title = "Complete Quiz - ISO/OSI and TCP/IP models"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
